package cmd

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/rs/zerolog/log"
	"github.com/spf13/cobra"

	"github.com/skillledger/skillledger/internal/proxy"
)

var proxyTrustCmd = &cobra.Command{
	Use:   "trust",
	Short: "Install proxy CA into system trust store",
	Long: `Installs the SkillLedger proxy CA certificate into the operating system's
trust store. This enables HTTPS interception without certificate warnings.

On macOS, the certificate is added to the System keychain.
On Linux, it is copied to /usr/local/share/ca-certificates and
update-ca-certificates is run.

This command may require elevated privileges (sudo on Linux, admin on macOS).
Use --yes to skip the confirmation prompt.`,
	RunE: runProxyTrust,
}

func runProxyTrust(cmd *cobra.Command, args []string) error {
	baseDir := proxyBaseDir()
	certPath := proxy.CACertPath(baseDir)

	// Check that the CA certificate exists.
	if _, err := os.Stat(certPath); os.IsNotExist(err) {
		return fmt.Errorf("no CA certificate found at %s\nRun `skillledger proxy start` first to generate one", certPath)
	}

	// Warn user about what this does (T-09-08: never auto-install).
	fmt.Println("WARNING: This will install the SkillLedger proxy CA certificate into")
	fmt.Println("your system trust store. This allows the proxy to intercept HTTPS traffic.")
	fmt.Println("The CA is local to this machine and generated by SkillLedger.")
	fmt.Printf("Certificate: %s\n", certPath)

	skipConfirm, _ := cmd.Flags().GetBool("yes")
	if !skipConfirm {
		fmt.Print("\nContinue? [y/N] ")
		reader := bufio.NewReader(os.Stdin)
		response, err := reader.ReadString('\n')
		if err != nil {
			return fmt.Errorf("failed to read input: %w", err)
		}
		response = strings.TrimSpace(response)
		if response != "y" && response != "Y" {
			fmt.Println("Aborted.")
			return nil
		}
	}

	if err := proxy.InstallCATrust(certPath); err != nil {
		return fmt.Errorf("installing CA certificate: %w", err)
	}

	log.Info().Str("cert", certPath).Msg("CA certificate installed into system trust store")
	return nil
}

func init() {
	proxyTrustCmd.Flags().BoolP("yes", "y", false, "skip confirmation prompt")
}
