package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var proxyProfileCmd = &cobra.Command{
	Use:   "profile",
	Short: "Manage auto-profiled skill capabilities",
	Long:  `View and export draft capability manifests generated by auto-profiling.`,
}

var proxyProfileExportCmd = &cobra.Command{
	Use:   "export <skill-id>",
	Short: "Export draft capability manifest for a profiled skill",
	Long: `Exports the auto-profiled capability manifest from ~/.skillledger/profiles/<skill-id>.yaml.
The draft manifest can be reviewed, edited, and adopted as the skill's official manifest.

The proxy writes profiles to this directory on shutdown.`,
	Args: cobra.ExactArgs(1),
	RunE: runProxyProfileExport,
}

var proxyProfileListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all auto-profiled skills",
	Long: `Lists all auto-profiled skills from ~/.skillledger/profiles/.
The proxy writes draft manifests to this directory on shutdown.`,
	RunE: runProxyProfileList,
}

func runProxyProfileExport(cmd *cobra.Command, args []string) error {
	skillID := args[0]
	baseDir := proxyBaseDir()
	profileDir := filepath.Join(baseDir, "profiles")
	profilePath := filepath.Join(profileDir, skillID+".yaml")

	data, err := os.ReadFile(profilePath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("no profile found for skill %q at %s\nRun the proxy with the skill active to generate a profile", skillID, profilePath)
		}
		return fmt.Errorf("reading profile: %w", err)
	}

	fmt.Print(string(data))
	return nil
}

type profileListEntry struct {
	SkillID string `json:"skill_id"`
	File    string `json:"file"`
	Size    int64  `json:"size"`
}

func runProxyProfileList(cmd *cobra.Command, args []string) error {
	baseDir := proxyBaseDir()
	profileDir := filepath.Join(baseDir, "profiles")

	entries, err := os.ReadDir(profileDir)
	if err != nil {
		if os.IsNotExist(err) {
			if jsonOutput {
				fmt.Println("[]")
				return nil
			}
			fmt.Println("No profiles directory found. Run the proxy to generate profiles.")
			return nil
		}
		return fmt.Errorf("reading profiles directory: %w", err)
	}

	var profiles []profileListEntry
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if !strings.HasSuffix(name, ".yaml") && !strings.HasSuffix(name, ".yml") {
			continue
		}
		skillID := strings.TrimSuffix(strings.TrimSuffix(name, ".yaml"), ".yml")
		info, err := entry.Info()
		if err != nil {
			continue
		}
		profiles = append(profiles, profileListEntry{
			SkillID: skillID,
			File:    filepath.Join(profileDir, name),
			Size:    info.Size(),
		})
	}

	if jsonOutput {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		if len(profiles) == 0 {
			fmt.Println("[]")
			return nil
		}
		return enc.Encode(profiles)
	}

	if len(profiles) == 0 {
		fmt.Println("No profiles found. Run the proxy with skills active to generate profiles.")
		return nil
	}

	fmt.Printf("%-30s  %-50s  %s\n", "SKILL ID", "FILE", "SIZE")
	fmt.Printf("%-30s  %-50s  %s\n", strings.Repeat("-", 30), strings.Repeat("-", 50), strings.Repeat("-", 8))
	for _, p := range profiles {
		fmt.Printf("%-30s  %-50s  %d bytes\n", p.SkillID, p.File, p.Size)
	}

	return nil
}

func init() {
	proxyProfileCmd.AddCommand(proxyProfileExportCmd)
	proxyProfileCmd.AddCommand(proxyProfileListCmd)
}
