name: Validate Threat Library

on:
  pull_request:
    paths:
      - 'threat-library/**'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v5.0.0
        with:
          python-version: '3.12'
      - run: pip install jsonschema
      - run: python scripts/validate-threat-library.py
